# Generated by Django 4.2 on 2024-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='modified_by_signal',
            field=models.BooleanField(default=False),
        ),
    ]
